package com.wewash.services.mapper.marketset;

public enum BetgeniusOutcomeType {
    BG_OUTCOME_HOME(1),
    BG_OUTCOME_DRAW(2),
    BG_OUTCOME_AWAY(3),
    BG_OUTCOME_HANDICAP_HOME(4),
    BG_OUTCOME_HANDICAP_AWAY(5),
    BG_OUTCOME_SOCCER_HANDICAP_DRAW(6),
    BG_OUTCOME_SOCCER_HOME_DRAW(7),
    BG_OUTCOME_SOCCER_HOME_AWAY(8),
    BG_OUTCOME_SOCCER_AWAY_DRAW(9),
    BG_OUTCOME_SOCCER_HOME_HOME_FULL_HALFTIME(10),
    BG_OUTCOME_SOCCER_HOME_DRAW_FULL_HALFTIME(11),
    BG_OUTCOME_SOCCER_HOME_AWAY_FULL_HALFTIME(12),
    BG_OUTCOME_SOCCER_DRAW_HOME_FULL_HALFTIME(13),
    BG_OUTCOME_SOCCER_DRAW_DRAW_FULL_HALFTIME(14),
    BG_OUTCOME_SOCCER_DRAW_AWAY_FULL_HALFTIME(15),
    BG_OUTCOME_SOCCER_AWAY_HOME_FULL_HALFTIME(16),
    BG_OUTCOME_SOCCER_AWAY_DRAW_FULL_HALFTIME(17),
    BG_OUTCOME_SOCCER_AWAY_AWAY_FULL_HALFTIME(18),
    BG_OUTCOME_NO_CARD(19),
    BG_OUTCOME_SOCCER_NO_GOAL(21),
    BG_OUTCOME_SOCCER_DRAW_HALF(27),
    BG_OUTCOME_SOCCER_FIRST_HALF(28),
    BG_OUTCOME_SOCCER_SECOND_HALF(29),
    BG_OUTCOME_OVER(30),
    BG_OUTCOME_UNDER(31),
    BG_OUTCOME_SOCCER_EVEN(32),
    BG_OUTCOME_SOCCER_ODD(33),
    BG_OUTCOME_NO_RELATED_EVENT_POINT(34),
    BG_OUTCOME_YES(39),
    BG_OUTCOME_NO(40),
    BG_OUTCOME_ANY_OTHER(64),
    BG_OUTCOME_REGULAR_HOME(75),
    BG_OUTCOME_OVERTIME_HOME(76),
    BG_OUTCOME_PENALTIES_HOME(77),
    BG_OUTCOME_REGULAR_AWAY(78),
    BG_OUTCOME_OVERTIME_AWAY(79),
    BG_OUTCOME_PENALTIES_AWAY(80),
    BG_OUTCOME_SOCCER_HOME_OVER(102),
    BG_OUTCOME_SOCCER_HOME_UNDER(103),
    BG_OUTCOME_SOCCER_DRAW_OVER(104),
    BG_OUTCOME_SOCCER_DRAW_UNDER(105),
    BG_OUTCOME_SOCCER_AWAY_OVER(106),
    BG_OUTCOME_SOCCER_AWAY_UNDER(107);

    private int id;

    BetgeniusOutcomeType(int id) {
        this.id= id;

    }

    public int getId() {
        return id;
    }
}
