package com.wewash.services.domain.ebet.dto.enums;

public enum EbetBetMarketType {
    ASCENDENCY("ascendency"),
    CORNER_KICKS_MORE_LESS_REST("corner-kicks-more-less-rest"),
    CORNER_KICKS_MORE_LESS_REST_HT("corner-kicks-more-less-rest-ht"),
    CORRECT_SCORE_LIVE("correct-score-live"),
    CUSTOM_POINTS_MORE_LESS_THAN("custom-points-more-less-than"),
    DEUCE_IN_GAME("deuce-in-game"),
    DOUBLE_CHANCE("double-chance"),
    FIRST_GAME_POINTS("first-game-points"),
    FIRST_SCORER("first-scorer"),
    FIRST_SCORER_HALFTIME("first-scorer-halftime"),
    FRAME_SCORE("frame-score"),
    GAME_WIN("game-win"),
    GAME_HANDICAP("game-handicap"),
    GAME_HANDICAP_IN_SET("game-handicap-in-set"),
    GAMES_MORE_LESS_THAN("games-more-less-than"),
    HALFTIME_FULLTIME("halftime-fulltime"),
    HALFTIME_WIN("halftime-win"),
    HANDICAP("handicap"),
    HANDICAP_HALFTIME("handicap-halftime"),
    INNING_SCORE("inning-score"),
    KO_YES_NO("ko-yes-no"),
    MORE_CORNER_KICKS("more-corner-kicks"),
    MORE_CORNER_KICKS_REST("more-corner-kicks-rest"),
    NEXT_CORNER_KICK("next-corner-kick"),
    CORNER_KICK_HANDICAP("corner-kick-handicap"),
    CORNER_KICKS_MORE_LESS_THAN("corner-kicks-more-less-than"),
    NUMBER_OF_CORNER_KICKS("number-of-corner-kicks"),
    NEXT_POINT("next-point"),
    NEXT_POINT_HALFTIME("next-point-halftime"),
    PENALTY_SCORED_1("penalty-scored-1"),
    PENALTY_SCORED_2("penalty-scored-2"),
    POINT_BET_HALFTIME("point-bet-halftime"),
    POINTS_MORE_LESS_REST("points-more-less-rest"),
    POINTS_MORE_LESS_REST_HALFTIME("points-more-less-rest-halftime"),
    POINTS_MORE_LESS_HALFTIME("points-more-less-halftime"),
    POINTS_MORE_LESS_THAN("points-more-less-than"),
    RACE_WINNER("race-winner"),
    SCORE_BOTH_HALFTIME("score-both-halftime"),
    SECTION_CORNER_KICKS("section-corner-kicks"),
    SECTION_GAMES_MORE_LESS("section-games-more-less"),
    SECTION_HANDICAP("section-handicap"),
    SECTION_POINTS_MORE_LESS("section-points-more-less"),
    SECTION_WIN("section-win"),
    SET_SCORE("set-score"),
    STANDARD("standard"),
    STANDARD_REST("standard-rest"),
    STANDARD_REST_HALFTIME("standard-rest-halftime"),
    TEAM_POINTS_MORE_LESS("team-points-more-less"),
    TOTALS_TEAM_WINS("totals-team-wins"),
    TEAM_TO_WIN_TO_NIL("team-to-win-to-nil"),
    ODD_EVEN("odd-even"),
    TYPE_OF_ADVANCE("type-of-advance"),
    NEXT_YELLOW_CARD("next-yellow-card"),
    MORE_HALFTIME_POINTS("more-halftime-points"),
    NUMBER_OF_POINTS_2("number-of-points-2"),
    NUMBER_OF_POINTS("number-of-points"),
    DOUBLE_CHANCE_FIRST_HALF("double-chance-first-half"),
    TEAM_NUMBER_OF_POINTS("team-number-of-points"),
    GOAL_SCORER("goal-scorer"),
    GOAL_SCORER_HALFTIME("goal-scorer-halftime"),
    GOAL_SCORER_TEAM_WINS("goal-scorer-team-wins"),
    GOAL_SCORER_MIN_2("goal-scorer-min-2"),
    PLAYER_YELLOW_CARD("player-yellow-card"),
    CUSTOM_1_X_2("custom1X2"),
    CUSTOM_RACE_BET("custom-race-bet"),
    CUSTOM_YES_NO("custom-yes-no"),
    CUSTOM_PLACE_YES_NO("custom-place-yes-no"),
    CUSTOM_MORE_LESS_THAN("custom-more-less-than"),
    CUSTOM_HEAD_TO_HEAD("custom-head-to-head"),
    ASIAN_HANDICAP("asian-handicap"),
    SCORE_BOTH("score-both"),
    HEAD_TO_HEAD("head-to-head"),
    TEAM_SCORES("team-scores"),
    ASIAN_HANDICAP_HALFTIME("asian-handicap-halftime"),
    POINT_MINUTE("point-minute"),
    GOAL_SCORE_MIN_2("goal-score-min-2"),
    MORE_YELLOW_CARDS("more-yellow-cards"),
    YELLOW_CARDS_MORE_LESS_THAN("yellow-cards-more-less-than");

    private String id;

    EbetBetMarketType(final String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }
}