package com.wewash.services.domain.ebet.dto.enums;

public enum EbetOutcomeType {
    EBET_OUTCOME_OVER("+"),
    EBET_OUTCOME_UNDER("-"),
    EBET_OUTCOME_YES("J"),
    EBET_OUTCOME_NO("N"),
    EBET_OUTCOME_ANY_OTHER("X:X"),
    EBET_OUTCOME_HOME("1"),
    EBET_OUTCOME_DRAW("X"),
    EBET_OUTCOME_AWAY("2"),
    EBET_OUTCOME_SECOND_HALF("2"),
    EBET_OUTCOME_FIRST_HALF("1"),
    EBET_OUTCOME_DRAW_HALF("X"),
    EBET_OUTCOME_SOCCER_NO_GOAL("X"),
    EBET_OUTCOME_SOCCER_HOME_DRAW("1X"),
    EBET_OUTCOME_SOCCER_HOME_AWAY("12"),
    EBET_OUTCOME_SOCCER_AWAY_DRAW("X2"),
    EBET_OUTCOME_SOCCER_HOME_OVER("1+"),
    EBET_OUTCOME_SOCCER_HOME_UNDER("1-"),
    EBET_OUTCOME_SOCCER_AWAY_OVER("2+"),
    EBET_OUTCOME_SOCCER_AWAY_UNDER("2-"),
    EBET_OUTCOME_SOCCER_DRAW_OVER("X+"),
    EBET_OUTCOME_SOCCER_DRAW_UNDER("X-"),
    EBET_OUTCOME_SOCCER_HOME_HOME_FULL_HALFTIME("1:1"),
    EBET_OUTCOME_SOCCER_HOME_DRAW_FULL_HALFTIME("1:X"),
    EBET_OUTCOME_SOCCER_HOME_AWAY_FULL_HALFTIME("1:2"),
    EBET_OUTCOME_SOCCER_DRAW_HOME_FULL_HALFTIME("X:1"),
    EBET_OUTCOME_SOCCER_DRAW_DRAW_FULL_HALFTIME("X:X"),
    EBET_OUTCOME_SOCCER_DRAW_AWAY_FULL_HALFTIME("X:2"),
    EBET_OUTCOME_SOCCER_AWAY_HOME_FULL_HALFTIME("2:1"),
    EBET_OUTCOME_SOCCER_AWAY_DRAW_FULL_HALFTIME("2:X"),
    EBET_OUTCOME_SOCCER_AWAY_AWAY_FULL_HALFTIME("2:2"),
    EBET_OUTCOME_SOCCER_EVEN("E"),
    EBET_OUTCOME_SOCCER_ODD("O"),
    EBET_OUTCOME_REGULAR_HOME("regular:1"),
    EBET_OUTCOME_OVERTIME_HOME("overtime:1"),
    EBET_OUTCOME_PENALTIES_HOME("penalties:1"),
    EBET_OUTCOME_REGULAR_AWAY("regular:2"),
    EBET_OUTCOME_OVERTIME_AWAY("overtime:2"),
    EBET_OUTCOME_PENALTIES_AWAY("penalties:2");

    String id;
    EbetOutcomeType(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }
}
