spring:
  application:
    name: import-service
  datasource:
    defaultAutoCommit: false
    validationQuery: SELECT 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 300000
    initialSize: 10
    maxActive: 20
    maxIdle: 10
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  h2:
    console:
      enabled: true

bx:
  security:
    betgenius:
      username: betgenius
      password: betgenius123
    actuator:
      username: actuator
      password: actuator123

server:
  port: 8888

logging:
  file: logs/import-service.log
  level:
    com.wewash: DEBUG

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

message-audit:
  audit-dir: audit/messages
  audit-enabled: true

debug-options:
  processing-enabled: true
  publishing-enabled: false
  store-intermediate-snapshots: false


management:
  context-path: /-system
  security:
    enabled: true

endpoints:
  health:
    sensitive: false
  info:
    sensitive: false


send-configuration:
    info-server-port: 12343
    info-server-url: http://localhost:${send-configuration.info-server-port}
    event-import-url: ${send-configuration.info-server-url}/event-import/v1/snapshots
    user: admin
    password: dummy
    http-pool:
      default-max-per-route: 20
      max-pool-size: 200

service:
    import-service:
      providerId: 71
      providerName: betgenius_v3
      heartbeatForwardEnabled: false